___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/6gCsHd6/1200px-Pandas-logo-svg.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Pandas DataFrames</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [DATA FRAMES](#1)
* [CREATING A DATA FRAME](#2)
    * [Creating a DataFrame Using the Lists of Data & Columns](#2.1)
    * [Creating a DataFrame Using a Numpy Arrays](#2.2)
    * [Creating a DataFrame Using a Dictionary](#2.3)
    * [The Examination of Some Attributes on Data](#2.4)
* [INDEXING, SLICING & SELECTION](#3)    
* [CREATING A NEW COLUMN](#4)    
* [REMOVING COLUMNS](#5)
* [REMOVING ROWS](#6)
* [SELECTING ROWS & COLUMNS USING .loc[ ] & .iloc[ ] ](#7)
* [CONDITIONAL SELECTION](#8)
    * [One Conditional Statement](#8.1)
    * [Two or More Conditional Statements](#8.2)
    * [Conditional Selection Using .loc[ ]](#8.3)
* [reset_index() & set_index()](#9)
* [Multi-Index & Index Hierarchy](#10)
* [Some Other Useful Methods with Iris Dataset](#11)
* [THE END OF THE SESSION-04](#12)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy & Pandas you can import them as a library:

In [3]:
import pandas as pd
import numpy as np

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Data Frames</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

A DataFrame is a two-dimensional data container, similar to a Matrix, but which can contain heterogeneous data, and for which symbolic names may be associated with the rows and columns. ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. 

### Why use Pandas?

Data scientists make use of Pandas in Python for its **following advantages**:

- Easily handles missing data
- It uses Series for one-dimensional data structure and DataFrame for multi-dimensional data structure
- It provides an efficient way to slice the data
- It provides a flexible way to merge, concatenate or reshape the data
- It includes a powerful time series tool to work with

In a nutshell, Pandas is a useful library in data analysis. It can be used to perform data manipulation and analysis. Pandas provide powerful and easy-to-use data structures, as well as the means to quickly perform operations on these structures.

[SOURCE01](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html), 
[SOURCE02](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html), 
[SOURCE03](https://morioh.com/p/2528ac775b1b), 
[SOURCE04](https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python), 
[SOURCE05](https://www.guru99.com/python-pandas-tutorial.html), 
[SOURCE06](https://www.tutorialspoint.com/python_pandas/python_pandas_dataframe.htm), 
[SOURCE07](https://realpython.com/pandas-dataframe/) &
[SOURCE08](https://towardsdatascience.com/a-simple-guide-to-pandas-dataframes-b125f64e1453)<br>
[VIDEO SOURCE01](https://www.youtube.com/watch?v=zmdjNSmRXF4), 
[VIDEO SOURCE02](https://www.youtube.com/watch?v=F6kmIpWWEdU) &
[VIDEO SOURCE03](https://towardsdatascience.com/pandas-dataframe-basics-3c16eb35c4f3)<br>

**Now let's use pandas to explore this topic!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Creating a DataFrame</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

A **``DataFrame``** is a **two-dimension collection of data**. It is a data structure where data is stored in **tabular form**. Datasets are arranged in rows and columns; we can store multiple datasets in the data frame. We can perform various arithmetic operations, such as adding column/row selection and columns/rows in the data frame.

We can import the DataFrames from the external storage; these storages can be referred to as the SQL Database, CSV file, and an Excel file. We can also use the lists, dictionary, and from a list of dictionary, etc.

In this session, we will learn to create the DataFrame in multiple ways. Let's understand these different ways.

**``pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)``**

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Creating a DataFrame Using the Lists of Data & Columns</p>

<a id="2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [4]:
pd.read_csv("IMDB_top_1000_LV.csv")

Movie_ID                     Title Certificate  Duration   
0           1  The Shawshank Redemption         13+       142  \
1           2             The Godfather          16       175   
2           3           The Dark Knight          16       152   
3           4    The Godfather: Part II          12       202   
4           5              12 Angry Men          14        96   
..        ...                       ...         ...       ...   
995       996    Breakfast at Tiffany's          AL       115   
996       997                     Giant           G       201   
997       998     From Here to Eternity          12       118   
998       999                  Lifeboat         NaN        97   
999      1000              The 39 Steps          14        86   

                        Genre  Rate  Metascore   
0                       Drama   9.3         80  \
1                Crime, Drama   9.2        100   
2        Action, Crime, Drama   9.0         84   
3                Crime, Drama   9.0         90   
4                Crime, Drama   9.0         96   
..                        ...   ...        ...   
995    Comedy, Drama, Romance   7.6         76   
996            Drama, Western   7.6         84   
997       Drama, Romance, War   7.6         85   
998                Drama, War   7.6         78   
999  Crime, Mystery, Thriller   7.6         93   

                                           Description  Year   
0    Two imprisoned men bond over a number of years...  1994  \
1    An organized crime dynasty's aging patriarch t...  1972   
2    When the menace known as the Joker wreaks havo...  2008   
3    The early life and career of Vito Corleone in ...  1974   
4    A jury holdout attempts to prevent a miscarria...  1957   
..                                                 ...   ...   
995  A young New York socialite becomes interested ...  1961   
996  Sprawling epic covering the life of a Texas ca...  1956   
997  In Hawaii in 1941, a private is cruelly punish...  1953   
998  Several survivors of a torpedoed merchant ship...  1944   
999  A man in London tries to help a counter-espion...  1935   

                Directors                                              Stars   
0          Frank Darabont  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...  \
1    Francis Ford Coppola  Marlon Brando, Al Pacino, James Caan, Diane Ke...   
2       Christopher Nolan  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
3    Francis Ford Coppola  Al Pacino, Robert De Niro, Robert Duvall, Dian...   
4            Sidney Lumet  Henry Fonda, Lee J. Cobb, Martin Balsam, John ...   
..                    ...                                                ...   
995         Blake Edwards  Audrey Hepburn, George Peppard, Patricia Neal,...   
996        George Stevens  Elizabeth Taylor, Rock Hudson, James Dean, Car...   
997        Fred Zinnemann  Burt Lancaster, Montgomery Clift, Deborah Kerr...   
998      Alfred Hitchcock  Tallulah Bankhead, John Hodiak, Walter Slezak,...   
999      Alfred Hitchcock  Robert Donat, Madeleine Carroll, Lucie Mannhei...   

       Votes  Gross($M)  
0    2377444      28.34  
1    1646788     134.97  
2    2341216     534.86  
3    1146645      57.30  
4     701877       4.36  
..       ...        ...  
995   168708       0.00  
996    34593       0.00  
997    43867      30.50  
998    26791       0.00  
999    52686       0.00  

[1000 rows x 13 columns]

In [5]:
my_list = [['John', 25, 'Male'],
           ['Alice', 30, 'Female'],
           ['Bob', 35, 'Male']]

In [6]:
df = pd.DataFrame()

In [7]:
list(enumerate(my_list))

[(0, ['John', 25, 'Male']),
 (1, ['Alice', 30, 'Female']),
 (2, ['Bob', 35, 'Male'])]

In [8]:
for i, col in list(enumerate(my_list)):
    df[i] = col
df

0       1     2
0  John   Alice   Bob
1    25      30    35
2  Male  Female  Male

In [9]:
df.columns = ["Name", "Age", "Gender"]

In [10]:
df

Name     Age Gender
0  John   Alice    Bob
1    25      30     35
2  Male  Female   Male

In [11]:
my_list = [['John', 25, 'Male'],
           ['Alice', 30, 'Female'],
           ['Bob', 35, 'Male']]
labels = ["Name", "Age", "Gender"]

In [12]:
pd.DataFrame.from_records(my_list, columns = labels)

Name  Age  Gender
0   John   25    Male
1  Alice   30  Female
2    Bob   35    Male

In [14]:
my_data = [1, 3, 5, 7, 9, 18]
my_data

[1, 3, 5, 7, 9, 18]

In [15]:
pd.DataFrame(data = my_data, columns = ["column1"])

column1
0        1
1        3
2        5
3        7
4        9
5       18

In [24]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df1 = pd.DataFrame(data)

In [17]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [25]:
df2 = df1

In [26]:
df2.drop("A", axis = 1, inplace = True)
df2

B
0  4
1  5
2  6

In [21]:
df1

B
0  4
1  5
2  6

In [27]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df1 = pd.DataFrame(data)

In [28]:
df2 = pd.DataFrame(df1, copy=True)
df2

A  B
0  1  4
1  2  5
2  3  6

In [29]:
df2.drop("A", axis = 1, inplace = True)
df2

B
0  4
1  5
2  6

In [30]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [31]:
df2 is df1

False

In [32]:
df2 = df1.copy()

In [33]:
pd.Series(data = my_data, name = "column_1")

0     1
1     3
2     5
3     7
4     9
5    18
Name: column_1, dtype: int64

In [34]:
pd.DataFrame(my_data)

0
0   1
1   3
2   5
3   7
4   9
5  18

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Creating a DataFrame Using a Numpy Arrays</p>

<a id="2.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [37]:
my_arr = np.arange(1, 24, 2).reshape(3, 4)
my_arr

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [45]:
df = pd.DataFrame(data = my_arr, columns = ("var1", "var2", "var3", "var4")

SyntaxError: incomplete input (4152672019.py, line 1)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Creating a DataFrame Using a Dictionary</p>

<a id="2.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [39]:
s1 = np.random.randint(2, 10, size = 4)
s2 = np.random.randint(3, 10, size = 4)
s3 = np.random.randint(4, 15, size = 4)

In [40]:
s1

array([9, 9, 7, 8])

In [41]:
s2

array([6, 7, 8, 6])

In [42]:
s3

array([14,  9,  8,  9])

In [43]:
myDict = {"var1": s1, "var2": s2, "var3": s3}
myDict

{'var1': array([9, 9, 7, 8]),
 'var2': array([6, 7, 8, 6]),
 'var3': array([14,  9,  8,  9])}

In [48]:
df = pd.DataFrame(myDict)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">The Examination of Some Attributes on Data</p>

<a id="2.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [49]:
df.head(2)

var1  var2  var3
0     9     6    14
1     9     7     9

In [50]:
df.tail(3)

var1  var2  var3
1     9     7     9
2     7     8     8
3     8     6     9

In [51]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [52]:
for i in df.columns:
    print(i)

var1
var2
var3


In [53]:
myDict

{'var1': array([9, 9, 7, 8]),
 'var2': array([6, 7, 8, 6]),
 'var3': array([14,  9,  8,  9])}

In [54]:
myDict["var1"]

array([9, 9, 7, 8])

In [55]:
df["var1"]

0    9
1    9
2    7
3    8
Name: var1, dtype: int32

In [56]:
type(df["var1"])

pandas.core.series.Series

In [57]:
for i in df.columns:
    print(df[i].mean())

8.25
6.75
10.0


In [58]:
for i in df.columns:
    print(df[i].min())

7
6
8


In [59]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [60]:
[i for i in df.index]

[0, 1, 2, 3]

In [61]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [62]:
df.columns = "new1", "new2", "new3"
df

new1  new2  new3
0     9     6    14
1     9     7     9
2     7     8     8
3     8     6     9

In [63]:
df.index = ["a","b","c","d"]
df

new1  new2  new3
a     9     6    14
b     9     7     9
c     7     8     8
d     8     6     9

In [66]:
df.rename(columns = {"new1": "yeni1","new2": "yeni2"})

yeni1  yeni2  new3
a      9      6    14
b      9      7     9
c      7      8     8
d      8      6     9

In [65]:
df

new1  new2  new3
a     9     6    14
b     9     7     9
c     7     8     8
d     8     6     9

In [68]:
df.rename(index = {"a":1,"b":2})


new1  new2  new3
1     9     6    14
2     9     7     9
c     7     8     8
d     8     6     9

In [71]:
original_length = df.shape[0]
original_length

4

In [72]:
df.values

array([[ 9,  6, 14],
       [ 9,  7,  9],
       [ 7,  8,  8],
       [ 8,  6,  9]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Indexing, Slicing & Selection</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's learn a variety of methods to grab data from a DataFrame

In [73]:
from numpy.random import randn

In [74]:
# creating a DataFrame by "keyword arguments"

np.random.seed(101)
df = pd.DataFrame(randn(5, 4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [75]:
df["Y"]

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [76]:
df.Y

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [77]:
df[["Y"]]

Y
A  0.907969
B -0.848077
C  0.528813
D -0.933237
E  2.605967

In [79]:
df[["Y"]]["A":"C"]

Y
A  0.907969
B -0.848077
C  0.528813

In [81]:
df["A":"C"][["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001

In [ ]:
df[["W","Z"]]

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Creating a New Column</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [82]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [84]:
df["new1"] = df["X"]*df["Y"]
df

W         X         Y         Z      new1
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [86]:
df["new2"] = np.arange(5)
df

W         X         Y         Z      new1  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     0
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     1
C -2.018168  0.740122  0.528813 -0.589001  0.391387     2
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     3
E  0.190794  1.978757  2.605967  0.683509  5.156577     4

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Removing Columns</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Removing Rows</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Selecting Rows and Columns using .loc[ ] and iloc[ ]</p>

<a id="7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [89]:
data = np.random.randint(1, 40, size=(8, 4))

df = pd.DataFrame(data, columns = ["var1", "var2", "var3", 'var4'], index = "A B C D E F G H".split())
df

var1  var2  var3  var4
A    12    11    31    36
B    29     4    20    21
C    15     6     6     7
D    25    38     8    38
E     5    24    36    16
F    35     4    19    14
G     4    38    30    23
H    22    22    18    24

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Conditional Selection</p>

<a id="8"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">One Conditional Statement</p>

<a id="8.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Two or More Conditional Statements</p>

<a id="8.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**For two or more conditions, you can use | → or, & → and with parenthesis:**

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Conditional Selection Using .loc[ ] and .iloc[ ]</p>

<a id="8.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [88]:
df.loc["a":"f"]

Empty DataFrame
Columns: [var1, var2, var3, var4]
Index: []

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">reset_index() & set_index()</p>

<a id="9"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [90]:
df.reset_index(drop=True, inplace=True)
df

var1  var2  var3  var4
0    12    11    31    36
1    29     4    20    21
2    15     6     6     7
3    25    38     8    38
4     5    24    36    16
5    35     4    19    14
6     4    38    30    23
7    22    22    18    24

In [93]:
df.set_index("var4",inplace=True)
df

KeyError: "None of ['var4'] are in the columns"

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Multi-Index & Index Hierarchy</p>

<a id="10"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [94]:
# Index Levels

outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2','M3', 'M3', 'M3']
inside = [1, 2, 3, 1, 2, 3, 5, 6, 7]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 1),
 ('M2', 2),
 ('M2', 3),
 ('M3', 5),
 ('M3', 6),
 ('M3', 7)]

In [95]:
pd.MultiIndex.from_tuples(multi_index)

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           )

In [96]:
hier_index = pd.MultiIndex.from_tuples(multi_index)
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           )

In [98]:
np.random.seed(101)

df = pd.DataFrame(np.random.randn(9,4), index = hier_index, columns=["A B C D".split()])
df

A         B         C         D
M1 1  2.706850  0.628133  0.907969  0.503826
   2  0.651118 -0.319318 -0.848077  0.605965
   3 -2.018168  0.740122  0.528813 -0.589001
M2 1  0.188695 -0.758872 -0.933237  0.955057
   2  0.190794  1.978757  2.605967  0.683509
   3  0.302665  1.693723 -1.706086 -1.159119
M3 5 -0.134841  0.390528  0.166905  0.184502
   6  0.807706  0.072960  0.638787  0.329646
   7 -0.497104 -0.754070 -0.943406  0.484752

In [100]:
df.index.names = ["Group","Num"]
df.index.names

FrozenList(['Group', 'Num'])

In [101]:
df.index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           names=['Group', 'Num'])

In [102]:
df.index.levels

FrozenList([['M1', 'M2', 'M3'], [1, 2, 3, 5, 6, 7]])

In [103]:
df.index.levels[0]

Index(['M1', 'M2', 'M3'], dtype='object', name='Group')

In [104]:
df.index.get_level_values

<bound method MultiIndex.get_level_values of MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           names=['Group', 'Num'])>

In [105]:
df.index.get_level_values(1)

Index([1, 2, 3, 1, 2, 3, 5, 6, 7], dtype='int64', name='Num')

In [106]:
df.index.get_level_values("Group")

Index(['M1', 'M1', 'M1', 'M2', 'M2', 'M2', 'M3', 'M3', 'M3'], dtype='object', name='Group')

**``Note``** that all of the MultiIndex constructors accept a names argument which stores string names for the levels themselves. If no names are provided, None will be assigned:

For more information Indexing and Selecting Data, visit [**Pandas Official Documentation**](https://pandas.pydata.org/pandas-docs/version/0.13.0/indexing.html)

Now let's show how to index this! For index hierarchy we use ``df.loc[]``, if this was on the columns axis, you would just use normal bracket notation ``df[]``. Calling one level of the index returns the sub-dataframe:

More information for Multiindex and Advanced Indexing, visit [**Pandas Official Documentation**](https://pandas.pydata.org/docs/user_guide/advanced.html)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Some Other Useful Methods with Iris Dataset</p>

<a id="11"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Let's apply functions/attributes/methods we have learnt for "iris dataset" 

In [ ]:
import seaborn as sns

In [ ]:
sns.get_dataset_names()

<a id="12"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________